name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Instalar dependências
        run: npm ci

      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps

      - name: Criar arquivo .env
        run: |
            echo "ADMIN_JWT_SECRET=${{ vars.ADMIN_JWT_SECRET }}"  >> .env
            echo "API_TOKEN_SALT=${{ vars.API_TOKEN_SALT }}"      >> .env
            echo "APP_KEYS=${{ vars.APP_KEYS }}"                  >> .env
            echo "DATABASE_CLIENT=${{ vars.DATABASE_CLIENT }}"    >> .env
            echo "DATABASE_FILENAME=${{ vars.DATABASE_FILENAME }}">> .env
            echo "DATABASE_SSL=${{ vars.DATABASE_SSL }}">> .env
            echo "HOST=${{ vars.HOST }}">> .env
            echo "JWT_SECRET=${{ vars.JWT_SECRET }}"  >> .env
            echo "PORT=${{ vars.PORT }}">> .env
            echo "TRANSFER_TOKEN_SALT=${{ vars.TRANSFER_TOKEN_SALT }}"  >> .env

      - name: Run Dev Strapi
        run: npm run dev

      #- name: Iniciar servidor
      #  run: npm run start &
      #  env:
      #    HOST: 0.0.0.0
      #    PORT: 1337

      - name: Aguardar servidor
        run: npx wait-on http://localhost:1337

      - name: Executar testes do Playwright
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
